version: "3"
services:
  database:
    image: "postgres"
    container_name: database
    env_file:
      - app/.env
    ports:
      - "5432:5432"

  web:
    container_name: phonebook
    restart: always
    build: .
    links:
      - database
    volumes:
      - ./app:/app
    ports:
      - "8000:8000"